@startumlinterface Chicken{fly--egg}interface HairTail{swim}EarthChicken --|>ChickenMarsChicken --|>ChickenEarthHairTail --|>HairTailMarsHairTail --|>HairTailinterface IFactory{    Bird createChicken();    --    Fish createHairTail();}EarthFactory -|>IFactoryMarsFactory --|>IFactoryEarthFactory ...>EarthChickenEarthFactory ..>EarthHairTailMarsFactory ..> MarsChickenMarsFactory ..> MarsHairTail@enduml